eCom.Web/ViewModels/ConfigViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eCom.Web.ViewModels
{
    public class EditConfigViewModel
    {
        [Required]
        public string Key { get; set; }

        [Required]
        public string Value { get; set; }
    }
}

eCom.Web/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eCom.Services;
using eCom.Web.ViewModels;

namespace eCom.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ConfigController : Controller
    {
        public JsonResult UpdateMainPicture(string imageUrl)
        {
            JsonResult json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            bool result = false;

            if(!string.IsNullOrEmpty(imageUrl))
            {
                result = ConfigurationService.Instance.UpdateMainPicture("MainImage", imageUrl);
            }

            if (result)
                json.Data = new { success = true };
            else
                json.Data = new { success = false, message = "Something went wrong." };

            return json;
        }

        public ActionResult EditConfigData()
        {
            ViewBag.ConfigKeys = ConfigurationService.Instance.GetKeysConfig();

            return View();
        }

        [HttpPost]
        public JsonResult EditConfigData(EditConfigViewModel editModel)
        {
            JsonResult  json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!ModelState.IsValid)
            {
                json.Data = new { success = false, message = "Invalid inputs."};

                return json;
            }

            var configFromDb = ConfigurationService.Instance.GetConfig(editModel.Key);

            configFromDb.Value = editModel.Value;

            var result = ConfigurationService.Instance.EditConfig(configFromDb);

            if (result)
                json.Data = new { success = true };
            else
                json.Data = new { success = false, message = "Something went wrong." };

            return json;
        }
    }
}

eCom.Web/Views/Config/EditConfigData.cshtml
@{
    ViewBag.Title = "EditConfigData";
}

<div id="containerDiv" class="container">

    <div class="col-md-12 mt-3 pt-5 pb-3">
        <div class="title-section">
            <h2 class="title">
                Setting
            </h2>
        </div>
    </div>

    @if (ViewBag.ConfigKeys != null)
    {
        <form id="editConfigForm" class="pt-5 pb-5">
            <div class="row mt-2">
                <div class="col-md-12">

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Key</label>
                                <select name="Key" id="selectKey" class="form-control">
                                    <option selected disabled>Select Key</option>
                                    @foreach (var configKey in ViewBag.ConfigKeys)
                                    {
                                        <option value="@configKey">@configKey</option>
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Value</label>
                                <input name="Value" class="form-control" required placeholder="Configration value..." />
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button type="button" class="btn btn-primary float-right" id="saveBtn"><i class="fa fa-save"></i> Save</button>
        </form>

    <script>

      @* validation form *@
        $('#editConfigForm').validate({
            rules: {
                Key: {
                    required: true,
                },
                Value: {
                    required: true,
                },
            },
            messages: {
                Key: {
                    required: 'Key is required.',
                },
                Value: {
                    required: 'Value is required.'
                },
            },
            errorClass: "text-danger"
        });

        $("#saveBtn").click(function () {

            if ($('#editConfigForm').valid()) {

                var name = $("#selectKey option:selected").text();
                swal({
                    title: "Confirm!",
                    text: "Are you sure? wanna change " + name + ".",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then(function (willEdit) {
                    if (willEdit) {

                        $.ajax({
                            url: '@Url.Action("EditConfigData", "Config")',
                            data: $("#editConfigForm").serialize(),
                            type: 'Post'
                        })
                        .done(function (result) {
                            if (result.success) {
                                swal(name + " Updated successfuly.", {
                                    icon: "success",
                                }).then(function () {
                                    location.reload();
                                });
                            } else {
                                swal("Failed", result.message, {
                                    icon: "warning",
                                })
                            }
                        })
                    }
                });
            } else {
                swal("Failed", "Invalid inputs.", {
                    icon: "warning",
                })
            }
    });
    </script>
        
    }
    else
    {
        <section class="flat-row main-shop shop-slidebar">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-danger">
                            No Configurations are maded.
                        </div>
                    </div>
                </div>
            </div>>
        </section>
    }
</div>