eCom.Web/ViewModels/CategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using eCom.Entities;
using System.ComponentModel.DataAnnotations;

namespace eCom.Web.ViewModels
{
    public class CategorySearchViewModel
    {
        public List<Category> Categories { get; set; }

        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }

    public class NewCategoryViewModel
    {
        [Required]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public bool IsFeatured { get; set; }
    }

    public class EditCategoryViewModel
    {
        public int Id { get; set; }

        [Required]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public bool IsFeatured { get; set; }
    }
}

eCom.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using eCom.Entities;
using eCom.Services;
using eCom.Web.ViewModels;

namespace eCom.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryTable(string search, int? pageNo)
        {
            var pageSize = ConfigurationService.Instance.PageSize();
            CategorySearchViewModel catModel = new CategorySearchViewModel();
    
            catModel.SearchTerm = search;
            pageNo = pageNo.HasValue && pageNo.Value > 0 ? pageNo.Value : 1;

            var totalRecords = CategoriesService.Instance.GetCategoriesCount(search);

            catModel.Categories = CategoriesService.Instance.GetCategories(search, pageNo.Value, pageSize);
       
            catModel.Pager = new Pager(totalRecords, pageNo, pageSize);

            return PartialView("_CategoryTable", catModel);
        }

        #region Category Creation
        [HttpGet]
        public ActionResult Create()
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("PageNotFound","Error");

            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(NewCategoryViewModel categoryModel)
         {
             if (!ModelState.IsValid)
             {
                 return new HttpStatusCodeResult(500);
             }

             var newCategory = new Category();
             newCategory.Name = categoryModel.Name;
             newCategory.Description = categoryModel.Description;
             newCategory.ImageUrl = categoryModel.ImageUrl;
             newCategory.IsFeatured = categoryModel.IsFeatured;

             CategoriesService.Instance.SaveCategory(newCategory);

             return RedirectToAction("CategoryTable");
        }
        #endregion

        #region Category Updation
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("PageNotFound", "Error");

            EditCategoryViewModel editModel = new EditCategoryViewModel();

            var categoryFromDb = CategoriesService.Instance.GetCategory(id);

            editModel.Id = categoryFromDb.Id;
            editModel.Name = categoryFromDb.Name;
            editModel.Description = categoryFromDb.Description;
            editModel.ImageUrl = categoryFromDb.ImageUrl;
            editModel.IsFeatured = categoryFromDb.IsFeatured;

            return PartialView(editModel);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel categoryModel)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(500);
            }

            var categoryFromDb = CategoriesService.Instance.GetCategory(categoryModel.Id);

            categoryFromDb.Name = categoryModel.Name;
            categoryFromDb.Description = categoryModel.Description;
            categoryFromDb.ImageUrl = categoryModel.ImageUrl;
            categoryFromDb.IsFeatured = categoryModel.IsFeatured;

            CategoriesService.Instance.UpdateCategory(categoryFromDb);

            return RedirectToAction("CategoryTable");
        }
        #endregion

        [HttpPost]
        public ActionResult Delete(int id)
        {
            CategoriesService.Instance.DeleteCategory(id);

            return RedirectToAction("CategoryTable");
        }
    }
}

eCom.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCom.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);

                file.SaveAs(filePath);

                json.Data = new { success = true, imageURL = string.Format("/Content/Images/{0}",fileName) };
            }
            catch (Exception ex)
            {
                json.Data = new { success = false, message = ex.Message };
            }

            return json;
        }
    }
}

eCom.Web/Views/Category/Create.cshtml
@{
    ViewBag.Title = "Create";

    var imageUrl = "/Content/Images/default.jpg";
}

<h2>Create Category</h2>

<form id="createCategoryForm">
    <div class="row mt-2">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name</label>
                <input name="name" class="form-control" required placeholder="Category name..." />
            </div>

            <div class="form-group">
                <label>Description</label>
                <input name="Description" class="form-control" placeholder="Description..." />
            </div>

            <div class="form-group">
                <label>Image</label>
                <input id="selectImage" class="form-control" name="Image" type="file" accept=".png, .jpg" />
                <input id="imageUrl" type="hidden" name="ImageUrl" />

            </div>

            <div class="form-group">
                <label>Is featured ?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input type="radio" name="IsFeatured" value="true" /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input type="radio" name="IsFeatured" value="false" /> False</label>
                    </div>
                </div>
            </div>

            <button type="button" class="btn btn-primary" id="saveBtn"><i class="fa fa-save"></i> Save</button>
            <button type="button" class="btn btn-primary" id="cancelBtn"><i class="fa fa-times fa-lg"></i> Cancel</button>
        </div>

        <div class="col-md-4">
            <div class="thumb">
                <img id="categoryImage" class="img-thumbnail img-fluid" src="@imageUrl" />
            </div>
        </div>
    </div>
</form>

<script>
    $("#selectImage").change(function () {
        var element = this;

        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Picture", file);
        }

        $.ajax({
            type: 'Post',
            url: '@Url.Action("UploadImage","Shared")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
        .done(function (response) {
            if (response.success) {
                $("#categoryImage").attr("src", response.imageURL);
                $("#imageUrl").val(response.imageURL);
            }
        })
        .fail(function () {
            alert("Fail");
        })
    })

    @* validation form *@
    $('#createCategoryForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            name: {
                required: 'Name is required.',
                minlength: 'Minimum length is 5',
                maxlength: 'Maximum length is 50'
            },
            Description: {
                maxlength: 'Maximum length is 500'
            }
        },
        errorClass: "text-danger"
    });

    $("#saveBtn").click(function () {
        if ($("#createCategoryForm").valid()) {
            $.ajax({
                url: '@Url.Action("Create","Category")',
                data: $("#createCategoryForm").serialize(),
                type: 'Post',
            })
            .done(function (result) {
                $("#tableContainer").html(result);
                $("#actionContainer").empty();
                focusElement("tableContainer");
            })
            .fail(function () {
                swal({
                    title: "Warning!",
                    text: "Please, Check your inputs.",
                    icon: "warning",
                    dangerMode: true,
                });
            });
        } else {
            swal({
                title: "Warning!",
                text: "Please, Check your inputs.",
                icon: "warning",
                dangerMode: true,
            });
        };
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").empty();
        focusElement("tableContainer");
    })
</script>

eCom.Web/Views/Category/Delete.cshtml
@model eCom.Entities.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure u wanna delete this category ?</h3>

<form method="post">
    <input type="hidden" name="Id" value="@Model.Id" />
    <button type="submit">Submit</button>
</form>

<a href="/index">Cancel</a>

eCom.Web/Views/Category/Edit.cshtml
@model eCom.Web.ViewModels.EditCategoryViewModel

@{
    ViewBag.Title = "Edit";
    
    var trueChecked = Model.IsFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.IsFeatured ? "checked" : string.Empty;
    var imageUrl = Model.ImageUrl != null ? Model.ImageUrl : "/content/images/default.jpg";
}

<h2>Edit Category</h2>

<form id="editCategoryForm">
    <div class="row mt-2">
        <div class="col-md-8">
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="form-group">
                <label>Name</label>
                <input name="name" class="form-control" required value="@Model.Name" placeholder="Category name..." />
            </div>

            <div class="form-group">
                <label>Description</label>
                <input name="Description" class="form-control" value="@Model.Description" placeholder="Description..." />
            </div>

            <div class="form-group">
                <label>Image</label>
                <input id="selectImage" class="form-control" name="Image" type="file" accept=".png, .jpg" />
                <input id="imageUrl" type="hidden" value="@Model.ImageUrl" name="ImageUrl" />

            </div>

            <div class="form-group">
                <label>Is featured ?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input type="radio" name="IsFeatured" value="true" @trueChecked /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input type="radio" name="IsFeatured" value="false" @falseChecked /> False</label>
                    </div>
                </div>
            </div>

            <button type="button" class="btn btn-primary" id="updateBtn"><i class="fa fa-save"></i> Update</button>
            <button type="button" class="btn btn-primary" id="cancelBtn"><i class="fa fa-times fa-lg"></i> Cancel</button>
        </div>

        <div class="col-md-4">
            <div class="thumb">
                <img id="categoryImage" class="img-thumbnail img-fluid" src="@imageUrl" />
            </div>
        </div>
    </div>
</form>

<script>
    $("#selectImage").change(function () {
        var element = this;

        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Picture", file);
        }

        $.ajax({
            type: 'Post',
            url: '@Url.Action("UploadImage","Shared")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
        .done(function (response) {
            if (response.success) {
                $("#categoryImage").attr("src", response.imageURL);
                $("#imageUrl").val(response.imageURL);
            }
        })
        .fail(function () {
            alert("Fail");
        })
    })

    @* Edit validation *@
    $('#editCategoryForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            }
        },
        messages: {
            name: {
                required: 'Name is required',
                minlength: 'Minimum length is 5',
                maxlength: 'Maximum length is 50'
            },
            Description: {
                maxlength: 'Maximum length is 500'
            }
        },
        errorClass: "text-danger"
    });

    $("#updateBtn").click(function () {
        if ($("#editCategoryForm").valid()) {
            $.ajax({
                url: '@Url.Action("Edit","Category")',
                data: $("#editCategoryForm").serialize(),
                type: 'Post',
            })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").empty();
                focusElement("tableContainer");
                debugger;
            })
              .fail(function () {
                  swal({
                      title: "Warning!",
                      text: "Please, Check your inputs.",
                      icon: "warning",
                      dangerMode: true,
                  });
              });
        } else {
            swal({
                title: "Warning!",
                text: "Please, Check your inputs.",
                icon: "warning",
                dangerMode: true,
            });
        }
    });


    $("#cancelBtn").click(function () {
        $("#actionContainer").empty();
        focusElement("tableContainer");
    })

    
</script>

eCom.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="container">

    <div class="col-md-12 mt-3">
        <div class="title-section">
            <h2 class="title">
                Categories
            </h2>
        </div>
    </div>
   
    <div id="tableContainer">
        @{
            Html.RenderAction("CategoryTable", "Category");
        }
    </div>

    <hr />

    <div id="actionContainer">

    </div>
</div>

eCom.Web/Views/Category/_CategoryTable.cshtml
@model eCom.Web.ViewModels.CategorySearchViewModel

@{
    ViewBag.Title = "Category Table";
}

<div class="col-md-12">
    <form id="controlForm">
        <div class="input-group mt-3 mb-3">
            <input id="searchTxt" name="Search" class="form-control mr-1" value="@Model.SearchTerm" placeholder="Search..." />
            <div class="input-group-append">
                <button type="button" id="searchBtn" class="btn btn-primary"><i class="fa fa-search"></i>  Search</button>
                <button type="button" id="resetBtn" class="btn btn-primary"><i class="fa fa-refresh"></i>  Reset</button>
                <button type="button" id="newCategoryBtn" class="btn btn-primary"><i class="fa fa-plus"></i>  New</button>
            </div>
        </div>
    </form>
</div>

@if(Model != null && Model.Categories != null && Model.Categories.Count() > 0)
{

<div class=" table-responsive">
    <table class="table table-striped" >
        <thead>
            <tr style="width:1%">
                <th class="font-weight-bold">Category</th>
                <th class="font-weight-bold">Products</th>
                <th class="font-weight-bold">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                    <tr>
                        <td class="font-weight-bold text-primary">@category.Name</td>
                        <td> <a href="@Url.Action("Index", "Product", new { categoryId = category.Id })"> @category.Products.Count </a></td>
                        <td>
                            <button class="editBtn" data-id="@category.Id"><i class="fa fa-pencil"></i> Edit</button>
                            <button class="deleteBtn" data-id="@category.Id" data-name="@category.Name"><i class="fa fa-trash"></i> Delete</button>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr><td colspan="3" class="text-danger">No categories found.</td></tr>
            }
        </tbody>
    </table>

    <div class="d-flex justify-content-center">
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {
            <nav aria-label="Page navigation example">
                <ul class="flat-pagination">
                    @if (Model.Pager.CurrentPage != 1)
                    {
                        <li class="page-item">
                            <button class="pageButtons page-link" data-pageno="1"><i class="fa fa-angle-double-left"></i></button>
                        </li>
                        <li class="page-item">
                            <button class="pageButtons page-link" data-pageno="@(Model.Pager.CurrentPage -1)"><i class="fa fa-angle-left"></i></button>
                        </li>
                    }

                    @for (int page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                    {
                        string activeClass = Model.Pager.CurrentPage == page ? "bg-danger" : string.Empty;

                        <li class="page-item">
                            <button class="pageButtons page-link @activeClass" data-pageno="@page">@page</button>
                        </li>
                    }
                    @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                    {
                        <li class="page-item">
                            <button class="pageButtons page-link" data-pageno="@(Model.Pager.CurrentPage +1)"><i class="fa fa-angle-right"></i></button>
                        </li>
                        <li class="page-item">
                            <button class="pageButtons page-link" data-pageno="@Model.Pager.EndPage"><i class="fa fa-angle-double-right"></i></button>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>
</div>
}
else
{
    <section class="flat-row main-shop shop-slidebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <i class="fa fa-bell"></i> No categories.
                    </div>
                </div>
            </div>
        </div>>
    </section>
}

<script>
    $(".pageButtons").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable","Category")',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm'
            },
        })
        .done(function (result) {
            $("#tableContainer").html(result);
            focusElement("tableContainer");
        })
        .fail(function () {
            alert("Fail");
        })
        debugger;
    });

    //search by click on search btn
    $("#searchBtn").click(function () {
        getAjaxSearch();
    });

    //search by press enter
    $("#controlForm").keypress(function (event) {
        if (event.keyCode == 13) // 13 is the keycode for enter
        {
            getAjaxSearch();
            return false;
        }
    });

    function getAjaxSearch() {
        var searchValue = $("#searchTxt").val();
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                search: searchValue
            },
            type: 'Get',
        })
         .done(function (result) {
             $("#tableContainer").html(result);
         })
         .fail(function () {
             alert("Fail");
         })
    }

    $("#resetBtn").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            type: 'Get',
        })
        .done(function (result) {
            $("#tableContainer").html(result);
            $("#actionContainer").empty();
        })
        .fail(function () {
            alert("Fail");
        })
    });

    $("#newCategoryBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create","Category")',
        })
        .done(function (result) {
            $("#actionContainer").html(result);

            focusElement("actionContainer");
        })
        .fail(function () {
            alert("Fail");
        })
    });

    $(".editBtn").click(function () {
        var id = $(this).attr("data-id");
        $.ajax({
            url: '@Url.Action("Edit", "Category")',
            data: {
                id: id
            }
        })
        .done(function (result) {
            $("#actionContainer").html(result);

            focusElement("actionContainer");
        })
        .fail(function () {
            alert("Fail");
        })
    });

    $(".deleteBtn").click(function () {
        var id = $(this).attr("data-id");
        var name = $(this).attr("data-name");

        swal({
            title: "Confirm!",
            text: "Are you sure. you wanna delete " + name + " ?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then(function (willDelete) {
            if (willDelete) {
                $.ajax({
                    url: '@Url.Action("Delete","Category")',
                    data: {
                        id: id
                    },
                    type: 'Post'
                })
                .done(function (result) {

                    swal(name + " deleted successfuly.", {
                        icon: "success",
                    });

                    $("#tableContainer").html(result);
                    $("#actionContainer").empty();
                })
                .fail(function () {
                    alert("Fail");
                });
            }
        });
    });
</script>