eCom.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using eCom.Services;
using eCom.Entities;
using eCom.Web.ViewModels;

namespace eCom.Web.Controllers
{
    public class ProductController : Controller
    {
        #region User Manager
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductTable(string search,int? categoryId, int? pageNo)
        {
            var pageSize = ConfigurationService.Instance.PageSize();

            ProductSearchViewModel productModel = new ProductSearchViewModel();

            pageNo = pageNo.HasValue && pageNo.Value > 0 ? pageNo.Value : 1;

            productModel.SearchTerm = search;
            productModel.CategoryId = categoryId;
            var totalRecords = ProductService.Instance.GetProductsCount(search, categoryId);

            productModel.Products = ProductService.Instance.GetProducts(search, categoryId, pageNo.Value, pageSize);
            productModel.Categories = CategoriesService.Instance.GetCategories();

            productModel.Pager = new Pager(totalRecords, pageNo.Value, pageSize);

            return PartialView(productModel);

        }

        #region Product Creation
        [HttpGet]
        public ActionResult Create()
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("PageNotFound", "Error");

            NewProductViewModel productModel = new NewProductViewModel();

            productModel.AvailableCategories = CategoriesService.Instance.GetCategories();

            return PartialView(productModel);
        }

        [HttpPost]
        public ActionResult Create(NewProductViewModel productModel)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(500);
            }

            var newProduct = new Product();
            newProduct.Name = productModel.Name;
            newProduct.Description = productModel.Description;
            newProduct.Price = productModel.Price;
            newProduct.ImageUrl = productModel.ImageUrl;
            newProduct.Category = CategoriesService.Instance.GetCategory(productModel.CategoryId);

            ProductService.Instance.SaveProduct(newProduct);

            return RedirectToAction("ProductTable");
        }
        #endregion

        #region Product Updation
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (!Request.IsAjaxRequest())
                return RedirectToAction("PageNotFound", "Error");

            EditProductViewModel editModel = new EditProductViewModel();

            var productFromDb = ProductService.Instance.GetProduct(id);

            editModel.Id = productFromDb.Id;
            editModel.Name = productFromDb.Name;
            editModel.Description = productFromDb.Description;
            editModel.Price = productFromDb.Price;
            editModel.ImageUrl = productFromDb.ImageUrl;
            editModel.CategoryId = productFromDb.Category != null ? productFromDb.Category.Id : 0;

            editModel.Categories = CategoriesService.Instance.GetCategories();

            return PartialView(editModel);
        }

        [HttpPost]
        public ActionResult Edit(EditProductViewModel productModel)
        {
            if(!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(500);
            }

            var productFromDb = ProductService.Instance.GetProduct(productModel.Id);

            productFromDb.Name = productModel.Name;
            productFromDb.Description = productModel.Description;
            productFromDb.Price = productModel.Price;
            productFromDb.ImageUrl = productModel.ImageUrl;
            productFromDb.CategoryId = productModel.CategoryId;
            productFromDb.Category = CategoriesService.Instance.GetCategory(productModel.CategoryId);

            ProductService.Instance.UpdateProduct(productFromDb);

            return RedirectToAction("ProductTable");
        }

        #endregion

        [HttpGet]
        public ActionResult Details(int id)
        {
            ProductViewModel productModel = new ProductViewModel();

            productModel.Product = ProductService.Instance.GetProduct(id);
            productModel.AuthenticatedUser = UserManager.FindById(User.Identity.GetUserId());
            productModel.User = UserManager;

            if (productModel.Product != null && productModel.Product.Reviews != null && productModel.Product.Reviews.Count() > 0)
                productModel.RatesAvarage = ReviewService.Instance.GetRatesAvarage(id);

            if(productModel.AuthenticatedUser != null)
               productModel.IsProductWished = WishlistService.Instance.IsProductWished(productModel.AuthenticatedUser.Id, id);//check if user has wished this product before

            return View(productModel);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            ProductService.Instance.DeleteProduct(id);

            return RedirectToAction("ProductTable");
        }
    }
}

eCom.Web/Controllers/ReviewController.cs
using eCom.Entities;
using eCom.Services;
using eCom.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace eCom.Web.Controllers
{
    public class ReviewController : Controller
    {
        #region User Manager
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        public ActionResult AddReview(AddReviewViewModel addReviewModel)
        {
            if(!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(500);
            }

            bool result = false;

            var newReview = new Review();
            newReview.UserId = addReviewModel.UserId;
            newReview.Body = addReviewModel.Body;
            newReview.ReviewedAt = DateTime.Now;
            newReview.Rate = addReviewModel.Rate;
            newReview.ProductId = addReviewModel.ProductId;

            result = ReviewService.Instance.SaveReview(newReview);

            if (result)
                return RedirectToAction("_Reviews", new { productId = newReview.ProductId});

            return new HttpStatusCodeResult(500);
        }

        public PartialViewResult _Reviews(int productId)
        {
            var reviewsModel = new ReviewsViewModel();

            reviewsModel.Reviews = ReviewService.Instance.GetReviews(productId);
            reviewsModel.AuthenticatedUser = UserManager.FindById(User.Identity.GetUserId());
            reviewsModel.User = UserManager;

            reviewsModel.ProductId = productId;

            return PartialView(reviewsModel);
        }

        public ActionResult RemoveReview(int id, int productId)
        {
            ReviewService.Instance.RemoveReview(id);

            return RedirectToAction("_Reviews", new { productId = productId});
        }
    }
}

eCom.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCom.Web.Controllers
{
    public class SharedController : Controller
    {
        public JsonResult UploadImage()
        {
            JsonResult json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            try
            {
                var file = Request.Files[0];

                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var filePath = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);

                file.SaveAs(filePath);

                json.Data = new { success = true, imageURL = string.Format("/Content/Images/{0}",fileName) };
            }
            catch (Exception ex)
            {
                json.Data = new { success = false, message = ex.Message };
            }

            return json;
        }
    }
}

eCom.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eCom.Services;
using eCom.Web.ViewModels;
using eCom.Web.Code;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using eCom.Entities;
using eCom.Web.Models;

namespace eCom.Web.Controllers
{
    public class ShopController : Controller
    {
        #region User Manager
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        public ActionResult Index(int? categoryId) 
        {
            var shopModel = new ShopViewModel();

            shopModel.FilledCategories = CategoriesService.Instance.GetFilledCategories();

            shopModel.MaximumPrice = ProductService.Instance.GetMaxPrice();
            shopModel.CategoryId = categoryId;

            return View(shopModel);
        }

        public ActionResult FilterProducts(string searchTerm, decimal? minPrice, decimal? maxPrice, int? categoryId, byte? sortBy, int? pageNo)
        {
            var filterModel = new FilterProductViewModel();

            pageNo = pageNo.HasValue && pageNo.Value > 0 ? pageNo.Value : 1;
            var pageSize = ConfigurationService.Instance.ShopPageSize(); //6

            filterModel.SortBy = sortBy;
            filterModel.CategoryId = categoryId;
            filterModel.SearchTerm = searchTerm;

            filterModel.FilledCategories = CategoriesService.Instance.GetFilledCategories();

            filterModel.MaximumPrice = ProductService.Instance.GetMaxPrice();
            int totalRecords = ProductService.Instance.GetShopProductsCount(searchTerm, minPrice, maxPrice, categoryId, sortBy);

            filterModel.Products = ProductService.Instance.GetShopProducts(searchTerm, minPrice, maxPrice, categoryId, sortBy, pageNo.Value, pageSize);

            filterModel.Pager = new Pager(totalRecords, pageNo, pageSize);
            filterModel.User = UserManager.FindById(User.Identity.GetUserId());

            return PartialView(filterModel);
        }

        [Authorize]
        public ActionResult Checkout()
        {
            return View();
        }

        public PartialViewResult CheckoutPartial()
        {
            var checkoutModel = new CheckoutViewModel();

            var user = UserManager.FindById(User.Identity.GetUserId());

            var cartProductsCookie = Request.Cookies[user.Name.Replace(" ","") + "CartProducts"];

            if (cartProductsCookie != null && !string.IsNullOrEmpty(cartProductsCookie.Value))
            {
                var userName = cartProductsCookie.Value.Split('-').First().Replace("%40","@");
                if (userName == User.Identity.Name)
                {
                    checkoutModel.CartProductIds = cartProductsCookie.Value.Split('-').Skip(1).Select(int.Parse).ToList(); //total numbers

                    checkoutModel.CartProducts = ProductService.Instance.GetProducts(checkoutModel.CartProductIds); //products with the same ids (distinct)

                    checkoutModel.User = user;
                }
            }

            return PartialView(checkoutModel);
        }

        public JsonResult PlaceOrder(string productIds)
        {
            var json = new JsonResult();
            json.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            if (!string.IsNullOrEmpty(productIds))
            {
                var splitedProductIds = productIds.Split(new[] { '-' }).Select(int.Parse).ToList(); //[7,7,10,1]

                var boughtProducts = ProductService.Instance.GetProducts(splitedProductIds.Distinct().ToList()); //[7,10,1]

                Order newOrder = new Order();

                newOrder.UserId = User.Identity.GetUserId();
                newOrder.OrderedAt = DateTime.Now;
                newOrder.Status = "Pending";

                //Iterate over all splitedIds matched with distinct ids, counted ,then * of unit price then sum all to get total
                newOrder.TotalAmount = boughtProducts.Sum(bP => bP.Price * splitedProductIds.Where(pId => pId == bP.Id).Count());

                newOrder.OrderItems = new List<OrderItem>();
                newOrder.OrderItems.AddRange(boughtProducts.Select(bP => new OrderItem() { ProductId = bP.Id, Quantity = splitedProductIds.Where(pId => pId == bP.Id).Count() }));

                var rowsEffeced = OrderService.Instance.SaveOrder(newOrder);

                json.Data = new { success = true, rows = rowsEffeced };
            }
            else
            {
                 json.Data = new { success = false }; 
            }

            return json;
        }

        [HttpPost]
        public ActionResult UpdateUser(UserViewModel userModel)
        {
            if(ModelState.IsValid)
            {
                var userInDb = UserManager.FindById(User.Identity.GetUserId());
                userInDb.Name = userModel.Name;
                userInDb.Address = userModel.Address;
                userInDb.PhoneNumber = "(+20) " + userModel.PhoneNumber;
                IdentityResult result = UserManager.Update(userInDb);

                if (result.Succeeded)
                {
                    return RedirectToAction("CheckoutPartial");
                }
            }

            return new HttpStatusCodeResult(500);
        }

        [Authorize]
        public ActionResult OrderPlaced()
        {
            return View();
        }

        public ActionResult _OrderPlaced(int? pageNo)
        {
            OrderPlacedViewModel orderPlacedModel = new OrderPlacedViewModel();

            pageNo = pageNo.HasValue && pageNo.Value > 0 ? pageNo.Value : 1;
            var pageSize = ConfigurationService.Instance.ShopPageSize(); //6

            int totalRecords = OrderService.Instance.GetOrdersCountByUserId(User.Identity.GetUserId());

            orderPlacedModel.User = UserManager.FindById(User.Identity.GetUserId());

            orderPlacedModel.Orders = OrderService.Instance.GetOrdersByUserId(User.Identity.GetUserId(), pageNo.Value, pageSize);

            orderPlacedModel.Pager = new Pager(totalRecords, pageNo, pageSize);

            return PartialView(orderPlacedModel);
        }
    }
}

eCom.Web/Views/Product/Create.cshtml
@model eCom.Web.ViewModels.NewProductViewModel

@{
    ViewBag.Title = "Create";
    var imageUrl = "/Content/Images/default.jpg";
}

<h2>Create Product</h2>

<form id="createProductForm">
    <div class="row mt-2">
        <div class="col-md-8">

            <div class="row">
                @if(Model.AvailableCategories != null && Model.AvailableCategories.Count() > 0)
                {
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Category</label>
                            <select name="CategoryId" class="form-control">
                                @foreach (var category in Model.AvailableCategories)
                                {
                                    <option value="@category.Id">@category.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                }
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Name</label>
                        <input name="name" class="form-control" required placeholder="Product name..." />
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label>Description</label>
                <input name="Description" class="form-control" placeholder="Description..." />
            </div>

            <div class="form-group">
                <label>Price</label>
                <input type="number" name="Price" class="form-control" placeholder="Price..." />
            </div>

            <div class="form-group">
                <label>Image</label>
                <input id="selectImage" class="form-control" name="Image" type="file" accept=".png, .jpg" />
                <input id="imageUrl" type="hidden" name="ImageUrl" />

            </div>
        </div>

        <div class="col-md-4">
            <div class="thumb">
                <img id="productImage" class="img-thumbnail img-fluid" src="@imageUrl" />
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" id="saveBtn"><i class="fa fa-save"></i> Save</button>
    <button type="button" class="btn btn-primary" id="cancelBtn"><i class="fa fa-times fa-lg"></i> Cancel</button>

</form>


<script>
    $("#selectImage").change(function () {
        var element = this;

        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Picture", file);
        }

        $.ajax({
            type: 'Post',
            url: '@Url.Action("UploadImage","Shared")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
        .done(function (response) {
            if (response.success) {
                $("#productImage").attr("src", response.imageURL);
                $("#imageUrl").val(response.imageURL);
            }
        })
        .fail(function () {
            alert("Fail");
        })
    })

    @* validation form *@
    $('#createProductForm').validate({
        rules: {
            name: {
                required: true,
                minlength: 5,
                maxlength: 50
            },
            Description: {
                maxlength: 500
            },
            Price: {
                required: true,
                range: [1, 1000000]
            }
        },
        messages: {
            name: {
                required: 'Name is required.',
                minlength: 'Minimum length is 5',
                maxlength: 'Maximum length is 50'
            },
            Description: {
                maxlength: 'Maximum length is 500'
            },
            Price: {
                required: "Price is required.",
                range: 'Inavlid price.'
            }
        },
        errorClass: "text-danger"
    });


    $("#saveBtn").click(function () {
        if ($("#createProductForm").valid()) {
            $.ajax({
                url: '@Url.Action("Create","Product")',
                data: $("#createProductForm").serialize(),
                type: 'Post',
            })
            .done(function (result) {
                $("#tableContainer").html(result);
                $("#actionContainer").empty();
                focusElement("tableContainer");
            })
            .fail(function () {
                swal({
                    title: "Warning!",
                    text: "Please, Check your inputs.",
                    icon: "warning",
                    dangerMode: true,
                });
            });
        } else {
            swal({
                title: "Warning!",
                text: "Please, Check your inputs.",
                icon: "warning",
                dangerMode: true,
            });
        };
    });

    $("#cancelBtn").click(function () {
        $("#actionContainer").empty();
        focusElement("tableContainer");
    })
</script>

eCom.Web/Views/Product/Details.cshtml
@model ProductViewModel

@if (Model != null && Model.Product != null)
{
    var defaultImgUrl = "/Content/Images/default.jpg";
    var imageUrl = string.IsNullOrEmpty(Model.Product.ImageUrl) ? defaultImgUrl : Model.Product.ImageUrl;

    <!-- Page title -->
    <div class="page-title parallax parallax1">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-title-heading">
                        <h1 class="title">@Model.Product.Name</h1>
                    </div><!-- /.page-title-heading -->
                </div><!-- /.col-md-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div><!-- /.page-title -->

    <section class="flat-row main-shop shop-detail">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="wrap-flexslider">
                        <div class="inner">
                            <div class="flexslider style-1 has-relative">
                                <ul class="slides">
                                    <li data-thumb="@imageUrl">
                                        <img src="@imageUrl" class="img-thumbnail">
                                        <div class="flat-icon style-1">
                                            <a href="@imageUrl" class="zoom-popup"><span class="fa fa-search-plus"></span></a>
                                        </div>
                                    </li>
                                </ul>
                            </div><!-- /.flexslider -->
                        </div>
                    </div>
                </div><!-- /.col-md-6 -->

                <div class="col-md-6">
                    <div class="product-detail">
                        <div class="inner">
                            <div class="content-detail">
                                <h2 class="product-title">@Model.Product.Name</h2>
                                <p>@Model.Product.Description</p>
                                <div class="price">
                                    @*<del><span class="regular">$90.00</span></del>*@
                                    <ins>$<span class="amount text-danger">@Model.Product.Price</span></ins>
                                </div>
                                <div class="product-quantity">
                                    @if (User.Identity.IsAuthenticated)
                                    {
                                        <div class="add-to-cart">
                                            <span>Press again to add more.</span>
                                            <a class="productAddToCart" style="cursor:pointer" data-id="@Model.Product.Id">ADD TO CART</a>
                                        </div>
                                        <div class="box-like">
                                            @{
                                        var likedClass = Model.IsProductWished ? "fa fa-heart" : "fa fa-heart-o";
                                            }
                                            <a data-id="@Model.Product.Id" class="like" style="cursor:pointer"><i id="wishHeart" class="@likedClass"></i></a>
                                        </div>
                                    }

                                    <br />

                                    @if (Model.RatesAvarage.HasValue)
                                    {
                                        <div class="flat-star style-1">
                                            @for (int i = 0; i < Model.RatesAvarage.Value; i++)
                                            {
                                                <i class="fa fa-star"></i>
                                            }
                                        </div>
                                    }
                                    
                                </div>

                                <div class="product-categories">
                                    <span>Category: </span><a href="@Url.Action("Index", "Shop", new { categoryId = Model.Product.CategoryId })">@Model.Product.Category.Name</a>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.product-detail -->
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </section><!-- /.flat-row -->

    if (User.Identity.IsAuthenticated)
    {
        <section class="flat-row shop-detail-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="flat-tabs style-1 has-border">
                            <div id="reviewsDiv" class="inner">

                                @{
                                     Html.RenderAction("_Reviews", "Review", new { productId = Model.Product.Id });
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- /.shop-detail-content -->
    }

    //related products
    <section class="flat-row shop-related">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title-section margin-bottom-55">
                        <h2 class="title">Related Products</h2>
                    </div>
                    @{
    Html.RenderAction("Products", "Widgets", new { isLatestProducts = false, categoryId = Model.Product.CategoryId });
                    }
                </div>
            </div><!-- /.row -->
        </div>
    </section>
    
    var name = Model.AuthenticatedUser != null ? Model.AuthenticatedUser.Name.Replace(" ", "") : string.Empty;

    <script>
        $(".productAddToCart").click(function () {
    
            var existingCookieData = $.cookie('@name' + 'CartProducts');

            if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null) //undefined: first time
            {
                products = existingCookieData.split('-'); //split('-'): every item in index of string , split(): all items in one index of string
            } else {
                products = ['@User.Identity.Name']; //initialize
            }

            var productId = $(this).attr("data-id");
            products.push(productId);

            $.cookie('@name' + 'CartProducts', products.join('-'), { expires: 1, path: '/' }); // { path: '/'} to allow cookie in others controllers

            updateCartProducts($.cookie('@name' + 'CartProducts')); //count in layout (code in main.js)

            swal("Added to cart successfuly.", {
                icon: "success",
            });
        });


        $('.box-like').on('click', '.like', function () {
            var productId = $(this).attr("data-id");

            //add product to wishlist
            if ($("#wishHeart").hasClass("fa fa-heart-o")) {
                $.ajax({
                    url: '@Url.Action("AddWishlist", "Wishlist")',
                    data: {
                        productId: productId
                    },
                })
                .done(function (result) {
                    if (result.success) {
                        swal("Done", "Added to wishlist successfuly.", {
                            icon: "success",
                        });
                        $("#wishHeart").removeClass("fa fa-heart-o");
                        $("#wishHeart").addClass("fa fa-heart");
                    } else {
                        swal("Failed", result.message, {
                            icon: "warning",
                        });
                    }
                })
                .fail(function () {
                    alert("Fail");
                });
            } else { //remove product from wishlist

                $.ajax({
                    url: '@Url.Action("RemoveProduct", "Wishlist")',
                    data: {
                        productId: productId
                    },
                })
               .done(function (result) {
                   if (result.success) {
                       swal("Done", "Removed from wishlist successfuly.", {
                           icon: "success",
                       });
                       $("#wishHeart").removeClass("fa fa-heart");
                       $("#wishHeart").addClass("fa fa-heart-o");
                   } else {
                       swal("Failed", result.message, {
                           icon: "warning",
                       });
                   }
               })
               .fail(function () {
                   alert("Fail");
               });
            }
        });


    </script>

}
else
{
    <section class="flat-row main-shop shop-slidebar">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger">
                        <i class="fa fa-bell"></i> There is no product.
                    </div>
                </div>
            </div>
        </div>>
    </section>
}

eCom.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
}

<div class="container">

    <div class="col-md-12 mt-3">
        <div class="title-section">
            <h2 class="title">
                Products
            </h2>
        </div>
    </div>

    <div id="tableContainer">
        @{
            Html.RenderAction("ProductTable");
        }
    </div>
    <hr />
    <div id="actionContainer">

    </div>
</div>